spring.application.name=device-management

# --- Server Config ---
server.port=8080
server.error.include-stacktrace=never
# Improves security by preventing "Server: Tomcat" headers in responses
server.server-header=

# --- Database Persistence---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devicedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.h2.console.enabled=false

spring.jackson.mapper.accept-case-insensitive-enums=true

# --- Logging ---
logging.level.com.device.management=INFO
logging.level.org.springframework.web=WARN
logging.file.name=logs/device-management.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
# Log rotation to save disk space
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10MB

# --- Security ---
#spring.security.user.name=admin
#spring.security.user.password=${ADMIN_PASSWORD:admin123}